# Dockerfile for a sample container that runs NGINX web server and uses it to
# do SSL client verification, trusting the DoD PKI.
#
# In other words you can login to this web server and require CAC just like DoD
# websites do, but without having to go through DISA IASE. :) :) :)
#
# NGINX will set headers in this config (see default.conf) to let you extract
# the serial identifier and the subject name if you wish.

# TODO: NGINX maintains an official Docker image... is it better to start from
# that?
FROM alpine:latest

RUN apk update && apk add nginx && mkdir -p /run/nginx /www/data

# Provided in this Docker package, and relatively simple configs
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html   /www/data/index.html

# Generated by the Makefile. This is the server-side self-signed cert which the
# client will have to blindly trust.

# server cert
COPY certificate.pem /etc/nginx

# server privkey
COPY key.pem         /etc/nginx

# The Makefile will generate DoDRoots.crt (the DoD root + intermediate certs
# concatenated) by downloading the certs from the cyber.mil IASE website. NGINX
# needs these certs to setup the CA it trusts for client authentication.
#
# See also the default.conf's configuration where we permit NGINX to have
# multiple intermediate certs.
COPY DoDRoots.crt    /etc/nginx

EXPOSE 443/tcp

ENTRYPOINT ["/usr/sbin/nginx", "-q", "-g", "daemon off;"]
