# Dockerfile for a sample container that runs NGINX web server and uses it to
# do SSL client verification, trusting the DoD PKI.
#
# In other words you can login to this web server and require CAC just like DoD
# websites do, but without having to do through DISA IASE. :) :) :)
#
# NGINX will set headers in this config (see default.conf) to let you extract
# the serial identifier and the subject name if you wish.
FROM alpine:latest

RUN apk update && apk add nginx && mkdir -p /run/nginx && mkdir -p /www/data

# Provided in this Docker package, and relatively simple configs
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html   /www/data/index.html

# Generated by the Makefile
COPY certificate.pem /etc/nginx
COPY key.pem         /etc/nginx

# This is the only real 'tricky' part here. The DoDRoots.crt file must be manually
# generated at this point from the DoD Root CA certificates which are normally available
# from the DISA IASE PKI site (InstallRoot and friends). In my case these were literally
# a concatenation of DoD Root CA {2,3,4} into a single file, relying on Firefox to supply
# the intermediate certificates to chain to the client certificate.
COPY DoDRoots.crt    /etc/nginx

EXPOSE 443/tcp

ENTRYPOINT ["/usr/sbin/nginx", "-q", "-g", "daemon off;"]
